-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keep class org.openintents.openpgp.* implements android.os.Parcelable {}
-keep class org.openintents.ssh.authentication.* implements android.os.Parcelable {}
